services:
  Invit\PlivoBundle\Service\PlivoApi:
    arguments:
      - '%invit_plivo.auth.auth_id%'
      - '%invit_plivo.auth.auth_token%'

  Invit\PlivoBundle\Helper\PlivoHelper:
    arguments:
      - '%invit_plivo.auth.auth_token%'
